"use client"
import { useEffect,useState } from "react"
import { createClient } from "@/lib/supabase/client"
type Request={id:string;profile_id:string;name:string;email:string;subject:string;message:string;topic:string;status:string;created_at:string}
export default function ContactRequests(){
  const [rows,setRows]=useState<Request[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);const {data,error}=await createClient().from("contact_requests").select("*").order("created_at",{ascending:false}).limit(100);setError(error?.message||"");if(data)setRows(data);setLoading(false)}
  useEffect(()=>{void load()},[])
  const resolve=async(id:string)=>{const {error}=await createClient().from("contact_requests").update({status:"resolved"}).eq("id",id);if(error)setError(error.message);else void load()}
  const invite=async(row:Request)=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from("user_entitlements").upsert({profile_id:row.profile_id,entitlement_key:"creator_studio_access",source_type:"admin",source_id:user.id},{onConflict:"profile_id,entitlement_key,source_type,source_id"});if(error)setError(error.message);else await resolve(row.id)}
  return <section className="space-y-4"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">Contact and Studio invitation requests</h2><p className="mt-1 text-sm text-white/45">Requests submitted through the contact page appear here.</p></div><button onClick={()=>void load()} className="text-sm text-primary">Refresh</button></div>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{loading?<p className="text-sm text-white/45">Loading requests…</p>:!rows.length?<p className="text-sm text-white/45">No requests yet.</p>:rows.map(row=><article key={row.id} className="space-y-3 rounded-xl border border-white/10 p-5"><div className="flex justify-between gap-3"><h3 className="font-semibold">{row.subject}</h3><span className="text-xs text-primary">{row.status}</span></div><p className="text-xs text-white/50">{row.name} · {row.email} · {new Date(row.created_at).toLocaleString()}</p><p className="whitespace-pre-wrap text-sm text-white/75">{row.message}</p>{row.status==="pending"&&<div className="flex gap-4">{row.topic==="studio-access"&&<button onClick={()=>void invite(row)} className="rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-black">Grant Studio Invitation</button>}<button onClick={()=>void resolve(row.id)} className="text-xs text-white/65">Mark resolved</button></div>}</article>)}</section>
}
