"use client"

import Navbar from "@/components/Navbar"
import { useAuth } from "@/components/auth/auth-provider"
import { createClient } from "@/lib/supabase/client"
import { addStudioEpisode, addStudioShot, createStudioProject, deleteStudioProject, fetchProjectWorkspace, fetchStudioProjects, type StudioEpisode, type StudioProject, type StudioShot } from "@/lib/studio"
import { AnimatePresence, motion } from "framer-motion"
import { Clapperboard, Film, FolderPlus, Loader2, Plus, Sparkles, Trash2, X } from "lucide-react"
import { FormEvent, useEffect, useState } from "react"

const blankProject = { title: "", description: "", visual_style: "Cinematic", aspect_ratio: "16:9" }

export default function StudioPage() {
    const { user, loading, signInWithGoogle } = useAuth()
    const [projects, setProjects] = useState<StudioProject[]>([])
    const [active, setActive] = useState<StudioProject | null>(null)
    const [episodes, setEpisodes] = useState<StudioEpisode[]>([])
    const [shots, setShots] = useState<StudioShot[]>([])
    const [form, setForm] = useState(blankProject)
    const [creating, setCreating] = useState(false)
    const [busy, setBusy] = useState(false)
    const [error, setError] = useState("")

    const loadProjects = async () => { if (!user) return; try { setProjects(await fetchStudioProjects(createClient())) } catch { setError("Could not load your studio projects. Run the new Supabase migration first.") } }
    useEffect(() => { loadProjects() }, [user])
    const openProject = async (project: StudioProject) => { setActive(project); setError(""); try { const data = await fetchProjectWorkspace(createClient(), project.id); setEpisodes(data.episodes); setShots(data.shots) } catch { setError("Could not load this project workspace.") } }
    const addProject = async (event: FormEvent) => { event.preventDefault(); if (!user) return signInWithGoogle(); setBusy(true); setError(""); try { const project = await createStudioProject(createClient(), { ...form, profile_id: user.id }); setProjects((all) => [project, ...all]); setForm(blankProject); setCreating(false); await openProject(project) } catch { setError("Could not create project. Please ensure the Studio migration is applied.") } finally { setBusy(false) } }
    const removeProject = async (id: string) => { if (!confirm("Delete this project and all its episodes and shots?")) return; try { await deleteStudioProject(createClient(), id); setProjects((all) => all.filter((p) => p.id !== id)); if (active?.id === id) setActive(null) } catch { setError("Could not delete project.") } }
    const addEpisode = async () => { if (!active) return; const title = prompt("Episode title", `Episode ${episodes.length + 1}`)?.trim(); if (!title) return; try { const episode = await addStudioEpisode(createClient(), active.id, title, episodes.length); setEpisodes((all) => [...all, episode]) } catch { setError("Could not add episode.") } }
    const addShot = async (episode: StudioEpisode) => { const title = prompt("Shot title", `Shot ${shots.filter((s) => s.episode_id === episode.id).length + 1}`)?.trim(); if (!title) return; const promptText = prompt("Visual prompt (optional)") || ""; try { const shot = await addStudioShot(createClient(), episode.id, title, promptText, shots.filter((s) => s.episode_id === episode.id).length); setShots((all) => [...all, shot]) } catch { setError("Could not add shot.") } }

    return <main className="min-h-screen bg-[#050505] text-white"><Navbar /><div className="mx-auto max-w-7xl px-5 pb-20 pt-32">
        <div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 flex items-center gap-2 text-sm font-medium text-primary"><Sparkles className="h-4 w-4" /> AI CREATOR STUDIO</p><h1 className="text-4xl font-bold sm:text-5xl">Plan the story. Frame the shot.</h1><p className="mt-3 max-w-xl text-white/60">Organize your AI video ideas into projects, episodes, and shot prompts—ready for your production workflow.</p></div><button onClick={() => user ? setCreating(true) : signInWithGoogle()} className="btn-primary flex items-center gap-2"><FolderPlus className="h-4 w-4" /> New project</button></div>
        {error && <p className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>}
        {!user && !loading ? <div className="glass-card p-10 text-center"><Clapperboard className="mx-auto mb-4 h-10 w-10 text-primary" /><h2 className="text-xl font-semibold">Your creative workspace is waiting</h2><button onClick={signInWithGoogle} className="btn-primary mt-5">Sign in to use Studio</button></div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <motion.button layout key={project.id} onClick={() => openProject(project)} className="glass-card group min-h-52 p-6 text-left"><div className="mb-8 flex justify-between"><Film className="h-6 w-6 text-primary" /><button onClick={(e) => { e.stopPropagation(); removeProject(project.id) }} className="text-white/30 hover:text-red-400"><Trash2 className="h-4 w-4" /></button></div><h2 className="text-xl font-bold">{project.title}</h2><p className="mt-2 line-clamp-2 text-sm text-white/55">{project.description || "No project description yet."}</p><div className="mt-6 flex gap-2 text-xs text-white/45"><span className="rounded-full bg-white/10 px-3 py-1">{project.visual_style}</span><span className="rounded-full bg-white/10 px-3 py-1">{project.aspect_ratio}</span></div></motion.button>)}{user && projects.length === 0 && <button onClick={() => setCreating(true)} className="flex min-h-52 flex-col items-center justify-center rounded-xl border border-dashed border-white/20 text-white/50 hover:border-primary hover:text-primary"><Plus className="mb-2 h-7 w-7" /> Create your first project</button>}</div>}
    </div>
    <AnimatePresence>{creating && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-5"><motion.form initial={{ opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }} onSubmit={addProject} className="glass w-full max-w-lg rounded-2xl p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">New Studio Project</h2><button type="button" onClick={() => setCreating(false)}><X /></button></div><input required placeholder="Project title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mb-3 w-full rounded-lg border border-white/10 bg-black/30 p-3 outline-none focus:border-primary" /><textarea placeholder="What are you creating?" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mb-3 min-h-24 w-full rounded-lg border border-white/10 bg-black/30 p-3 outline-none focus:border-primary" /><div className="mb-5 grid grid-cols-2 gap-3"><select value={form.visual_style} onChange={(e) => setForm({ ...form, visual_style: e.target.value })} className="rounded-lg border border-white/10 bg-black p-3"><option>Cinematic</option><option>Photorealistic</option><option>Animation</option><option>Product ad</option></select><select value={form.aspect_ratio} onChange={(e) => setForm({ ...form, aspect_ratio: e.target.value })} className="rounded-lg border border-white/10 bg-black p-3"><option>16:9</option><option>9:16</option><option>1:1</option></select></div><button disabled={busy} className="btn-primary flex w-full justify-center gap-2">{busy && <Loader2 className="h-4 w-4 animate-spin" />} Create project</button></motion.form></div>}</AnimatePresence>
    <AnimatePresence>{active && <div className="fixed inset-0 z-[55] flex justify-end bg-black/55"><motion.aside initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }} className="h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-[#0a0a0a] p-6 sm:p-8"><div className="mb-8 flex justify-between gap-4"><div><p className="text-xs font-medium text-primary">PROJECT WORKSPACE</p><h2 className="mt-1 text-2xl font-bold">{active.title}</h2></div><button onClick={() => setActive(null)}><X /></button></div><button onClick={addEpisode} className="mb-6 flex items-center gap-2 rounded-lg border border-primary/40 px-4 py-2 text-sm text-primary hover:bg-primary/10"><Plus className="h-4 w-4" /> Add episode</button>{episodes.length === 0 ? <p className="rounded-xl border border-dashed border-white/15 p-8 text-center text-white/45">Start by adding an episode, then break it into individual shots.</p> : <div className="space-y-4">{episodes.map((episode) => <section key={episode.id} className="rounded-xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">{episode.title}</h3><button onClick={() => addShot(episode)} className="text-sm text-primary">+ Shot</button></div><div className="mt-4 space-y-2">{shots.filter((shot) => shot.episode_id === episode.id).map((shot) => <div key={shot.id} className="rounded-lg bg-black/30 p-3"><p className="text-sm font-medium">{shot.title}</p>{shot.prompt && <p className="mt-1 text-xs text-white/45">{shot.prompt}</p>}</div>)}{!shots.some((shot) => shot.episode_id === episode.id) && <p className="text-sm text-white/40">No shots yet.</p>}</div></section>)}</div>}</motion.aside></div>}</AnimatePresence>
    </main>
}
