-- Viewer analytics: who watched what, how far they got, and who is here now.
--
-- The catalogue has always been able to answer "who paid" — `originals_unlocks`
-- is that record. It has never been able to answer the questions that decide
-- what to shoot next: how many people started episode 4 and how many finished
-- it, where in an episode they leave, whether anyone comes back a second day,
-- and how many of the people on the site right now are watching rather than
-- browsing. None of that is derivable from purchases, because the interesting
-- losses happen before anyone is asked for money.
--
-- Three tables, in the order the funnel runs:
--
--   analytics_sessions    one visit, signed in or not
--   analytics_page_views  a path within that visit
--   originals_episode_views  one person's pass through one episode
--
-- Written only by the server. Every id in them comes from the browser except
-- `profile_id`, which is read from the session cookie in the ingest route — so
-- a client can inflate its own view counts but can never attribute a watch to
-- somebody else's account.
--
-- Anonymous visitors are first-class here. The opening episodes play with no
-- account at all (`originals_free_episode_url`), so an analytics table that
-- only understood `profile_id` would be blind to exactly the part of the funnel
-- where people decide whether to stay.

-- ---------------------------------------------------------------------------
-- 1. How recently is "here right now".
-- ---------------------------------------------------------------------------
-- The browser heartbeats every 30 seconds while the tab is visible, so a
-- window of two minutes survives one missed beat and a slow network without
-- counting someone who closed the tab four minutes ago. A function rather than
-- a literal because the live count and the live list must never disagree about
-- what live means.

create or replace function public.analytics_live_window()
returns interval
language sql immutable as $$
    select interval '2 minutes';
$$;

grant execute on function public.analytics_live_window() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 2. Sessions.
-- ---------------------------------------------------------------------------
-- `id` is generated by the browser and held in sessionStorage; `visitor_id`
-- lives in localStorage and outlives the tab. The pair is what separates "200
-- visits" from "200 people": visits count sessions, people count visitors.
--
-- `profile_id` is nullable and filled in late. A visit that starts signed out
-- and signs in halfway keeps the same row, which is the only way the funnel
-- from stranger to account holder stays a single story.

create table if not exists public.analytics_sessions (
    id uuid primary key,
    visitor_id uuid not null,
    profile_id uuid references public.profiles(id) on delete set null,
    started_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    page_views int not null default 0,
    landing_path text,
    referrer text,
    user_agent text,
    device text
);

-- The live list reads the newest rows and nothing else, so it leads.
create index if not exists analytics_sessions_live_idx
    on public.analytics_sessions (last_seen_at desc);
create index if not exists analytics_sessions_visitor_idx
    on public.analytics_sessions (visitor_id, started_at desc);
create index if not exists analytics_sessions_profile_idx
    on public.analytics_sessions (profile_id, started_at desc)
    where profile_id is not null;

create table if not exists public.analytics_page_views (
    id bigserial primary key,
    session_id uuid not null references public.analytics_sessions(id) on delete cascade,
    visitor_id uuid not null,
    profile_id uuid references public.profiles(id) on delete set null,
    path text not null,
    created_at timestamptz not null default now()
);

create index if not exists analytics_page_views_time_idx
    on public.analytics_page_views (created_at desc);
create index if not exists analytics_page_views_session_idx
    on public.analytics_page_views (session_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 3. Episode views.
-- ---------------------------------------------------------------------------
-- One row per session per episode, updated in place as the episode plays.
--
-- Two different numbers, because they answer different questions and one
-- cannot be recovered from the other:
--
--   seconds_watched  how much of it they actually sat through — the honest
--                    engagement number, blind to seeking
--   furthest_second  the deepest point reached — what a drop-off curve is
--                    drawn from, because someone who scrubs to the end and
--                    leaves did not watch the episode
--
-- `duration_seconds` is recorded per view rather than read from the episode
-- row at query time: the episode's own duration field is optional metadata an
-- admin types in, and a retention percentage computed against a wrong duration
-- is worse than no percentage at all.

create table if not exists public.originals_episode_views (
    id uuid primary key default gen_random_uuid(),
    session_id uuid not null references public.analytics_sessions(id) on delete cascade,
    visitor_id uuid not null,
    profile_id uuid references public.profiles(id) on delete set null,
    episode_id uuid not null references public.originals_episodes(id) on delete cascade,
    series_id uuid not null references public.originals_series(id) on delete cascade,
    started_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    seconds_watched int not null default 0,
    furthest_second int not null default 0,
    duration_seconds int,
    completed boolean not null default false,
    -- How it was being watched at the time: free | unlocked | pass | purchased.
    -- Kept on the view because entitlements expire — a rental that has since
    -- lapsed would otherwise make a past watch look like it was never paid for.
    access text not null default 'free',
    -- A second open of the same episode in the same visit is the same view,
    -- not a second one. Without this, a pause-and-resume would double the
    -- episode's view count and halve its apparent completion rate.
    unique (session_id, episode_id)
);

create index if not exists originals_episode_views_episode_idx
    on public.originals_episode_views (episode_id, started_at desc);
create index if not exists originals_episode_views_series_idx
    on public.originals_episode_views (series_id, started_at desc);
create index if not exists originals_episode_views_profile_idx
    on public.originals_episode_views (profile_id, started_at desc)
    where profile_id is not null;
create index if not exists originals_episode_views_visitor_idx
    on public.originals_episode_views (visitor_id, started_at desc);

-- ---------------------------------------------------------------------------
-- 4. RLS.
-- ---------------------------------------------------------------------------
-- No policies at all on any of the three. They are written by the ingest route
-- holding the service key and read by the admin functions below, both of which
-- bypass RLS — so an enabled-but-empty policy set is exactly right: nothing
-- reaches `anon` or `authenticated` directly.
--
-- This matters more than it looks. `analytics_page_views` is a record of where
-- every visitor went, and a SELECT policy generous enough to be useful to a
-- viewer would be generous enough to hand one viewer another's browsing.

alter table public.analytics_sessions enable row level security;
alter table public.analytics_page_views enable row level security;
alter table public.originals_episode_views enable row level security;

-- ---------------------------------------------------------------------------
-- 5. Ingest.
-- ---------------------------------------------------------------------------

-- A page view, or a bare heartbeat when `p_is_page_view` is false.
create or replace function public.record_site_visit(
    p_visitor_id uuid,
    p_session_id uuid,
    p_profile_id uuid,
    p_path text,
    p_referrer text,
    p_user_agent text,
    p_device text,
    p_is_page_view boolean default true
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_increment int := case when p_is_page_view then 1 else 0 end;
    v_profile_id uuid;
begin
    -- Called from the ingest route, which is the only thing that knows which
    -- account the cookie belongs to. Nothing else may write here.
    if coalesce(auth.role(), '') <> 'service_role' then
        raise exception 'Visits are recorded by the server only';
    end if;
    if p_visitor_id is null or p_session_id is null then
        raise exception 'A visitor and a session are required';
    end if;

    -- An authenticated user whose `profiles` row has not been created yet is
    -- recorded as anonymous rather than rejected. The alternative is a foreign
    -- key violation that fails the visit outright, and losing the visit to
    -- protect an attribution we can still pick up on the next request is the
    -- wrong trade.
    select p.id into v_profile_id from public.profiles p where p.id = p_profile_id;

    insert into public.analytics_sessions as s (
        id, visitor_id, profile_id, landing_path, referrer, user_agent, device, page_views
    )
    values (
        p_session_id, p_visitor_id, v_profile_id,
        left(p_path, 500), left(p_referrer, 500), left(p_user_agent, 400), left(p_device, 20),
        v_increment
    )
    on conflict (id) do update set
        last_seen_at = now(),
        -- Signing in mid-visit claims the visit. It never un-claims it: a
        -- sign-out later in the same session should not erase who was here.
        profile_id = coalesce(excluded.profile_id, s.profile_id),
        page_views = s.page_views + v_increment;

    if p_is_page_view then
        insert into public.analytics_page_views (session_id, visitor_id, profile_id, path)
        values (p_session_id, p_visitor_id, v_profile_id, left(p_path, 500));
    end if;
end;
$$;

revoke execute on function public.record_site_visit(uuid, uuid, uuid, text, text, text, text, boolean) from public, anon, authenticated;
grant execute on function public.record_site_visit(uuid, uuid, uuid, text, text, text, text, boolean) to service_role;

-- Progress through an episode. Called repeatedly as it plays, and once more
-- when the tab goes away, so every field folds rather than overwrites.
create or replace function public.record_episode_view(
    p_visitor_id uuid,
    p_session_id uuid,
    p_profile_id uuid,
    p_episode_id uuid,
    p_seconds_watched int,
    p_furthest_second int,
    p_duration_seconds int,
    p_completed boolean,
    p_access text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_series_id uuid;
    v_episode_duration int;
    v_duration int;
    v_profile_id uuid;
begin
    if coalesce(auth.role(), '') <> 'service_role' then
        raise exception 'Views are recorded by the server only';
    end if;
    if p_visitor_id is null or p_session_id is null or p_episode_id is null then
        raise exception 'A visitor, a session and an episode are required';
    end if;

    select e.series_id, e.duration_seconds into v_series_id, v_episode_duration
    from public.originals_episodes e where e.id = p_episode_id;
    if v_series_id is null then
        raise exception 'That episode does not exist';
    end if;

    -- What the player measured beats what an admin typed in; the episode row's
    -- duration is the fallback for a view that reported none.
    v_duration := coalesce(nullif(p_duration_seconds, 0), v_episode_duration);

    -- Same tolerance as record_site_visit: a missing profile row makes the
    -- watch anonymous rather than losing it.
    select p.id into v_profile_id from public.profiles p where p.id = p_profile_id;

    -- A watch can be the first thing a session reports — an episode opened from
    -- a shared link before the page-view beacon lands — so the session row is
    -- created here rather than assumed.
    insert into public.analytics_sessions as s (id, visitor_id, profile_id)
    values (p_session_id, p_visitor_id, v_profile_id)
    on conflict (id) do update set
        last_seen_at = now(),
        profile_id = coalesce(excluded.profile_id, s.profile_id);

    insert into public.originals_episode_views as v (
        session_id, visitor_id, profile_id, episode_id, series_id,
        seconds_watched, furthest_second, duration_seconds, completed, access
    )
    values (
        p_session_id, p_visitor_id, v_profile_id, p_episode_id, v_series_id,
        greatest(coalesce(p_seconds_watched, 0), 0),
        greatest(coalesce(p_furthest_second, 0), 0),
        v_duration,
        coalesce(p_completed, false),
        coalesce(nullif(btrim(p_access), ''), 'free')
    )
    on conflict (session_id, episode_id) do update set
        last_seen_at = now(),
        profile_id = coalesce(excluded.profile_id, v.profile_id),
        -- Monotonic, all of them. Reports can arrive out of order — a beacon
        -- fired on tab close can land after the heartbeat that followed it —
        -- and a late small number must not walk the progress backwards.
        seconds_watched = greatest(v.seconds_watched, excluded.seconds_watched),
        furthest_second = greatest(v.furthest_second, excluded.furthest_second),
        duration_seconds = coalesce(excluded.duration_seconds, v.duration_seconds),
        completed = v.completed or excluded.completed,
        access = excluded.access;
end;
$$;

revoke execute on function public.record_episode_view(uuid, uuid, uuid, uuid, int, int, int, boolean, text) from public, anon, authenticated;
grant execute on function public.record_episode_view(uuid, uuid, uuid, uuid, int, int, int, boolean, text) to service_role;

-- ---------------------------------------------------------------------------
-- 6. Housekeeping.
-- ---------------------------------------------------------------------------
-- `analytics_page_views` is the only table here that grows per click rather
-- than per person, so it is the only one that needs a broom. Sessions and
-- episode views are kept: they are what the per-viewer history is made of, and
-- they grow slowly enough to leave alone.

create or replace function public.prune_analytics_page_views(p_keep_days int default 180)
returns int
language plpgsql
security definer
set search_path = public
as $$
declare
    v_deleted int;
begin
    if coalesce(auth.role(), '') <> 'service_role'
       and not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    delete from public.analytics_page_views
    where created_at < now() - make_interval(days => greatest(coalesce(p_keep_days, 180), 7));
    get diagnostics v_deleted = row_count;
    return v_deleted;
end;
$$;

revoke execute on function public.prune_analytics_page_views(int) from public, anon;
grant execute on function public.prune_analytics_page_views(int) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7. Admin reads.
-- ---------------------------------------------------------------------------
-- Same shape as every other admin function in this schema: SECURITY DEFINER
-- with the check inside, so the admin page can call them with the user's own
-- session and there is exactly one place that decides who is an admin.
--
-- Throughout, a "person" is `coalesce(profile_id::text, visitor_id::text)` —
-- an account when there is one, a browser when there is not. Counting distinct
-- profiles alone would report that nobody watches the free episodes, which is
-- the opposite of true.

create or replace function public.admin_analytics_overview(p_days int default 30)
returns table (
    live_now int,
    live_watching int,
    live_signed_in int,
    visitors int,
    sessions int,
    page_views int,
    signed_in_visitors int,
    returning_visitors int,
    visitors_today int,
    visitors_previous_period int,
    episode_views int,
    episode_watchers int,
    episodes_completed int,
    avg_percent_watched numeric,
    paid_unlocks int,
    paying_viewers int,
    credits_spent int,
    season_passes int,
    pass_revenue_inr int
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_days int := greatest(coalesce(p_days, 30), 1);
    v_from timestamptz := now() - make_interval(days => v_days);
    -- The same length of time immediately before the window, so the headline
    -- number has something to be compared against.
    v_prev_from timestamptz := now() - make_interval(days => v_days * 2);
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    return query
    with live as (
        select s.id, s.profile_id
        from public.analytics_sessions s
        where s.last_seen_at > now() - public.analytics_live_window()
    ),
    live_watch as (
        select distinct v.session_id
        from public.originals_episode_views v
        join live l on l.id = v.session_id
        where v.last_seen_at > now() - public.analytics_live_window()
    ),
    window_sessions as (
        select s.* from public.analytics_sessions s where s.started_at >= v_from
    ),
    window_views as (
        select v.* from public.originals_episode_views v where v.started_at >= v_from
    )
    -- Every column below is table-qualified, deliberately. Half of these OUT
    -- parameters share a name with a column they are computed from
    -- (`page_views`, `credits_spent`), and plpgsql resolves the bare name to
    -- the variable, which is an ambiguity error at best and the wrong number
    -- at worst.
    select
        (select count(*)::int from live l),
        (select count(*)::int from live_watch lw),
        (select count(*)::int from live l where l.profile_id is not null),

        (select count(distinct ws.visitor_id)::int from window_sessions ws),
        (select count(*)::int from window_sessions ws),
        (select coalesce(sum(ws.page_views), 0)::int from window_sessions ws),
        (select count(distinct ws.profile_id)::int from window_sessions ws where ws.profile_id is not null),
        -- Came back: a visitor with more than one session inside the window.
        (select count(*)::int from (
            select ws.visitor_id from window_sessions ws group by ws.visitor_id having count(*) > 1
        ) r),
        (select count(distinct a.visitor_id)::int from public.analytics_sessions a
          where a.started_at >= date_trunc('day', now())),
        (select count(distinct a.visitor_id)::int from public.analytics_sessions a
          where a.started_at >= v_prev_from and a.started_at < v_from),

        (select count(*)::int from window_views wv),
        (select count(distinct coalesce(wv.profile_id::text, wv.visitor_id::text))::int from window_views wv),
        (select count(*)::int from window_views wv where wv.completed),
        (select round(avg(least(100, (wv.furthest_second * 100.0) / wv.duration_seconds)), 1)
           from window_views wv where coalesce(wv.duration_seconds, 0) > 0),

        (select count(*)::int from public.originals_unlocks u where u.created_at >= v_from),
        (select count(distinct u.profile_id)::int from public.originals_unlocks u where u.created_at >= v_from),
        (select coalesce(sum(u.credits_spent), 0)::int from public.originals_unlocks u where u.created_at >= v_from),
        (select count(*)::int from public.originals_season_passes sp where sp.created_at >= v_from),
        (select coalesce(sum(sp.price_inr), 0)::int from public.originals_season_passes sp where sp.created_at >= v_from);
end;
$$;

revoke execute on function public.admin_analytics_overview(int) from public, anon;
grant execute on function public.admin_analytics_overview(int) to authenticated, service_role;

-- One row per day, including the days nothing happened — a chart with the
-- empty days missing slopes through them and reads as steady traffic.
create or replace function public.admin_analytics_traffic(p_days int default 30)
returns table (
    day date,
    visitors int,
    sessions int,
    page_views int,
    episode_views int,
    paid_unlocks int,
    credits_spent int
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_days int := greatest(coalesce(p_days, 30), 1);
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    return query
    with days as (
        select generate_series(
            (date_trunc('day', now()) - make_interval(days => v_days - 1))::date,
            date_trunc('day', now())::date,
            interval '1 day'
        )::date as day
    ),
    session_days as (
        select date_trunc('day', s.started_at)::date as day,
               count(distinct s.visitor_id)::int as visitors,
               count(*)::int as sessions,
               coalesce(sum(s.page_views), 0)::int as page_views
        from public.analytics_sessions s
        where s.started_at >= date_trunc('day', now()) - make_interval(days => v_days - 1)
        group by 1
    ),
    view_days as (
        select date_trunc('day', v.started_at)::date as day, count(*)::int as episode_views
        from public.originals_episode_views v
        where v.started_at >= date_trunc('day', now()) - make_interval(days => v_days - 1)
        group by 1
    ),
    unlock_days as (
        select date_trunc('day', u.created_at)::date as day,
               count(*)::int as paid_unlocks,
               coalesce(sum(u.credits_spent), 0)::int as credits_spent
        from public.originals_unlocks u
        where u.created_at >= date_trunc('day', now()) - make_interval(days => v_days - 1)
        group by 1
    )
    select d.day,
           coalesce(sd.visitors, 0),
           coalesce(sd.sessions, 0),
           coalesce(sd.page_views, 0),
           coalesce(vd.episode_views, 0),
           coalesce(ud.paid_unlocks, 0),
           coalesce(ud.credits_spent, 0)
    from days d
    left join session_days sd on sd.day = d.day
    left join view_days vd on vd.day = d.day
    left join unlock_days ud on ud.day = d.day
    order by d.day;
end;
$$;

revoke execute on function public.admin_analytics_traffic(int) from public, anon;
grant execute on function public.admin_analytics_traffic(int) to authenticated, service_role;

-- Who is on the site this minute, and what they have open.
create or replace function public.admin_analytics_live()
returns table (
    session_id uuid,
    visitor_id uuid,
    profile_id uuid,
    full_name text,
    email text,
    avatar_url text,
    device text,
    path text,
    started_at timestamptz,
    last_seen_at timestamptz,
    series_title text,
    episode_number int,
    percent_watched int
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    return query
    select s.id,
           s.visitor_id,
           s.profile_id,
           p.full_name,
           p.email,
           p.avatar_url,
           s.device,
           -- Where they are: the newest path this session reported.
           (select pv.path from public.analytics_page_views pv
             where pv.session_id = s.id order by pv.created_at desc limit 1),
           s.started_at,
           s.last_seen_at,
           w.series_title,
           w.episode_number,
           w.percent_watched
    from public.analytics_sessions s
    left join public.profiles p on p.id = s.profile_id
    -- What they are watching, if anything: the episode this session touched
    -- most recently, and only while that touch is itself still live.
    left join lateral (
        select se.title as series_title,
               e.episode_number,
               case when coalesce(v.duration_seconds, 0) > 0
                    then least(100, ((v.furthest_second * 100) / v.duration_seconds))::int
                    else null end as percent_watched
        from public.originals_episode_views v
        join public.originals_episodes e on e.id = v.episode_id
        join public.originals_series se on se.id = v.series_id
        where v.session_id = s.id
          and v.last_seen_at > now() - public.analytics_live_window()
        order by v.last_seen_at desc
        limit 1
    ) w on true
    where s.last_seen_at > now() - public.analytics_live_window()
    order by s.last_seen_at desc;
end;
$$;

revoke execute on function public.admin_analytics_live() from public, anon;
grant execute on function public.admin_analytics_live() to authenticated, service_role;

-- Per-episode retention: how many started it, how far they got, how many went
-- on to the next one, and what it earned.
--
-- `continued_to_next` is the number that actually decides what to shoot. A
-- completion rate says an episode held the people who stayed; the walk-on rate
-- says the episode was good enough to spend money on the one after it.
create or replace function public.admin_analytics_episode_retention(p_series_id uuid default null)
returns table (
    episode_id uuid,
    series_id uuid,
    series_title text,
    episode_number int,
    episode_title text,
    is_published boolean,
    is_free boolean,
    duration_seconds int,
    views int,
    viewers int,
    signed_in_viewers int,
    avg_percent numeric,
    completions int,
    reached_25 int,
    reached_50 int,
    reached_75 int,
    reached_95 int,
    continued_to_next int,
    paid_unlocks int,
    credits_earned int
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    return query
    with viewer_episodes as (
        -- One row per person per episode, so the walk-on check below compares
        -- people rather than play events.
        select v.episode_id,
               v.series_id,
               coalesce(v.profile_id::text, v.visitor_id::text) as person
        from public.originals_episode_views v
        group by 1, 2, 3
    ),
    stats as (
        select v.episode_id,
               count(*)::int as views,
               count(distinct coalesce(v.profile_id::text, v.visitor_id::text))::int as viewers,
               count(distinct v.profile_id)::int as signed_in_viewers,
               round(avg(case when coalesce(v.duration_seconds, 0) > 0
                              then least(100, (v.furthest_second * 100.0) / v.duration_seconds)
                         end), 1) as avg_percent,
               count(*) filter (where v.completed)::int as completions,
               count(*) filter (where coalesce(v.duration_seconds, 0) > 0
                    and (v.furthest_second * 100.0) / v.duration_seconds >= 25)::int as reached_25,
               count(*) filter (where coalesce(v.duration_seconds, 0) > 0
                    and (v.furthest_second * 100.0) / v.duration_seconds >= 50)::int as reached_50,
               count(*) filter (where coalesce(v.duration_seconds, 0) > 0
                    and (v.furthest_second * 100.0) / v.duration_seconds >= 75)::int as reached_75,
               count(*) filter (where coalesce(v.duration_seconds, 0) > 0
                    and (v.furthest_second * 100.0) / v.duration_seconds >= 95)::int as reached_95
        from public.originals_episode_views v
        group by 1
    ),
    money as (
        select u.episode_id,
               count(*)::int as paid_unlocks,
               coalesce(sum(u.credits_spent), 0)::int as credits_earned
        from public.originals_unlocks u
        group by 1
    )
    select e.id,
           e.series_id,
           s.title,
           e.episode_number,
           e.title,
           e.is_published,
           e.episode_number <= s.free_episodes,
           e.duration_seconds,
           coalesce(st.views, 0),
           coalesce(st.viewers, 0),
           coalesce(st.signed_in_viewers, 0),
           st.avg_percent,
           coalesce(st.completions, 0),
           coalesce(st.reached_25, 0),
           coalesce(st.reached_50, 0),
           coalesce(st.reached_75, 0),
           coalesce(st.reached_95, 0),
           (select count(*)::int
              from viewer_episodes ve
              join public.originals_episodes ne
                on ne.series_id = e.series_id and ne.episode_number = e.episode_number + 1
             where ve.episode_id = e.id
               and exists (
                   select 1 from viewer_episodes nx
                    where nx.episode_id = ne.id and nx.person = ve.person
               )),
           coalesce(m.paid_unlocks, 0),
           coalesce(m.credits_earned, 0)
    from public.originals_episodes e
    join public.originals_series s on s.id = e.series_id
    left join stats st on st.episode_id = e.id
    left join money m on m.episode_id = e.id
    where p_series_id is null or e.series_id = p_series_id
    order by s.sort_order, s.title, e.episode_number;
end;
$$;

revoke execute on function public.admin_analytics_episode_retention(uuid) from public, anon;
grant execute on function public.admin_analytics_episode_retention(uuid) to authenticated, service_role;

-- Everyone who has opened one episode, and what each of them did with it.
create or replace function public.admin_analytics_episode_viewers(
    p_episode_id uuid,
    p_limit int default 200
)
returns table (
    profile_id uuid,
    visitor_id uuid,
    full_name text,
    email text,
    avatar_url text,
    views int,
    first_watched_at timestamptz,
    last_watched_at timestamptz,
    seconds_watched int,
    percent_watched int,
    completed boolean,
    access text,
    credits_spent int,
    paid_at timestamptz,
    unlock_expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    return query
    with per_person as (
        select coalesce(v.profile_id::text, v.visitor_id::text) as person,
               -- A person who watched signed out and then signed in has rows
               -- both ways; max() picks up the account when one exists.
               max(v.profile_id::text)::uuid as profile_id,
               max(v.visitor_id::text)::uuid as visitor_id,
               count(*)::int as views,
               min(v.started_at) as first_watched_at,
               max(v.last_seen_at) as last_watched_at,
               max(v.seconds_watched)::int as seconds_watched,
               max(case when coalesce(v.duration_seconds, 0) > 0
                        then least(100, (v.furthest_second * 100) / v.duration_seconds)
                        else 0 end)::int as percent_watched,
               bool_or(v.completed) as completed,
               -- Paid beats free when the same person has both: the question
               -- is whether they ever bought it, not how they last opened it.
               max(case v.access when 'purchased' then 4 when 'pass' then 3
                                 when 'unlocked' then 2 else 1 end) as access_rank
        from public.originals_episode_views v
        where v.episode_id = p_episode_id
        group by 1
    )
    select pp.profile_id,
           pp.visitor_id,
           p.full_name,
           p.email,
           p.avatar_url,
           pp.views,
           pp.first_watched_at,
           pp.last_watched_at,
           pp.seconds_watched,
           pp.percent_watched,
           pp.completed,
           case pp.access_rank when 4 then 'purchased' when 3 then 'pass'
                               when 2 then 'unlocked' else 'free' end,
           u.credits_spent,
           u.created_at,
           u.expires_at
    from per_person pp
    left join public.profiles p on p.id = pp.profile_id
    left join public.originals_unlocks u
           on u.episode_id = p_episode_id and u.profile_id = pp.profile_id
    order by pp.last_watched_at desc
    limit greatest(coalesce(p_limit, 200), 1);
end;
$$;

revoke execute on function public.admin_analytics_episode_viewers(uuid, int) from public, anon;
grant execute on function public.admin_analytics_episode_viewers(uuid, int) to authenticated, service_role;

-- One row per person: every visit, every episode, everything they paid.
--
-- `episodes_after_first_visit` is the returning-viewer answer — episodes whose
-- first watch happened in a visit that was not their first. Someone who binges
-- four episodes on day one and never comes back scores zero; someone who came
-- back the next evening for episode five scores one. That is the difference
-- between an audience and a day of traffic, and no count of sessions or
-- purchases separates them on its own.
create or replace function public.admin_analytics_viewers(
    p_days int default 90,
    p_limit int default 200,
    p_search text default null
)
returns table (
    profile_id uuid,
    visitor_id uuid,
    full_name text,
    email text,
    avatar_url text,
    first_seen_at timestamptz,
    last_seen_at timestamptz,
    sessions int,
    page_views int,
    episodes_watched int,
    episodes_completed int,
    episodes_after_first_visit int,
    watch_days int,
    seconds_watched int,
    paid_episodes int,
    credits_spent int,
    season_passes int,
    credits_balance int,
    last_series_title text,
    last_episode_number int
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_from timestamptz := now() - make_interval(days => greatest(coalesce(p_days, 90), 1));
    v_search text := nullif(btrim(coalesce(p_search, '')), '');
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    return query
    with sessions_in_window as (
        select s.*, coalesce(s.profile_id::text, s.visitor_id::text) as person
        from public.analytics_sessions s
        where s.started_at >= v_from
    ),
    people as (
        select sw.person,
               max(sw.profile_id::text)::uuid as profile_id,
               max(sw.visitor_id::text)::uuid as visitor_id,
               min(sw.started_at) as first_seen_at,
               max(sw.last_seen_at) as last_seen_at,
               count(*)::int as sessions,
               coalesce(sum(sw.page_views), 0)::int as page_views,
               -- The visit this person arrived on, which the "came back for a
               -- new episode" test below is measured against.
               (array_agg(sw.id order by sw.started_at))[1] as first_session_id
        from sessions_in_window sw
        group by sw.person
    ),
    views as (
        select coalesce(v.profile_id::text, v.visitor_id::text) as person,
               v.episode_id,
               min(v.started_at) as first_view_at,
               max(v.last_seen_at) as last_view_at,
               bool_or(v.completed) as completed,
               max(v.seconds_watched)::int as seconds_watched,
               (array_agg(v.session_id order by v.started_at))[1] as first_session_id
        from public.originals_episode_views v
        where v.started_at >= v_from
        group by 1, 2
    ),
    watch as (
        select vw.person,
               count(*)::int as episodes_watched,
               count(*) filter (where vw.completed)::int as episodes_completed,
               coalesce(sum(vw.seconds_watched), 0)::int as seconds_watched,
               count(distinct date_trunc('day', vw.first_view_at))::int as watch_days,
               max(vw.last_view_at) as last_view_at
        from views vw
        group by 1
    )
    select pe.profile_id,
           pe.visitor_id,
           p.full_name,
           p.email,
           p.avatar_url,
           pe.first_seen_at,
           pe.last_seen_at,
           pe.sessions,
           pe.page_views,
           coalesce(w.episodes_watched, 0),
           coalesce(w.episodes_completed, 0),
           (select count(*)::int from views vw
             where vw.person = pe.person
               and vw.first_session_id is distinct from pe.first_session_id),
           coalesce(w.watch_days, 0),
           coalesce(w.seconds_watched, 0),
           (select count(*)::int from public.originals_unlocks u where u.profile_id = pe.profile_id),
           (select coalesce(sum(u.credits_spent), 0)::int from public.originals_unlocks u where u.profile_id = pe.profile_id),
           (select count(*)::int from public.originals_season_passes sp where sp.profile_id = pe.profile_id),
           p.credits_balance,
           last_watch.series_title,
           last_watch.episode_number
    from people pe
    left join public.profiles p on p.id = pe.profile_id
    left join watch w on w.person = pe.person
    left join lateral (
        select se.title as series_title, e.episode_number
        from public.originals_episode_views v
        join public.originals_episodes e on e.id = v.episode_id
        join public.originals_series se on se.id = v.series_id
        where coalesce(v.profile_id::text, v.visitor_id::text) = pe.person
        order by v.last_seen_at desc
        limit 1
    ) last_watch on true
    where v_search is null
       or p.full_name ilike '%' || v_search || '%'
       or p.email ilike '%' || v_search || '%'
    order by pe.last_seen_at desc
    limit greatest(coalesce(p_limit, 200), 1);
end;
$$;

revoke execute on function public.admin_analytics_viewers(int, int, text) from public, anon;
grant execute on function public.admin_analytics_viewers(int, int, text) to authenticated, service_role;

-- Every purchase, newest first: who paid, for which episode, and how much.
-- Rentals and season passes in one list, because "which episodes has this
-- person paid for" has two answers and showing only unlocks understates it.
create or replace function public.admin_analytics_purchases(
    p_days int default 90,
    p_limit int default 300
)
returns table (
    kind text,
    profile_id uuid,
    full_name text,
    email text,
    avatar_url text,
    series_title text,
    episode_number int,
    episode_title text,
    credits_spent int,
    price_inr int,
    purchased_at timestamptz,
    expires_at timestamptz,
    watched boolean,
    percent_watched int
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_from timestamptz := now() - make_interval(days => greatest(coalesce(p_days, 90), 1));
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;

    -- The union is wrapped in a named CTE rather than ordered directly. A
    -- UNION's own ORDER BY may only name a result column, and every column
    -- here is an expression — so the bare `purchased_at` resolved to the OUT
    -- parameter of that name and Postgres rejected the whole statement. The
    -- explicit column list gives the ordering something real to point at.
    return query
    with purchase_rows (
        kind, profile_id, full_name, email, avatar_url, series_title,
        episode_number, episode_title, credits_spent, price_inr,
        purchased_at, expires_at, watched, percent_watched
    ) as (
    (
        select 'episode'::text,
               u.profile_id,
               p.full_name,
               p.email,
               p.avatar_url,
               s.title,
               e.episode_number,
               e.title,
               u.credits_spent,
               null::int,
               u.created_at,
               u.expires_at,
               -- Bought and never opened is worth seeing on its own: it is a
               -- refund conversation, and it is invisible in a revenue total.
               exists (
                   select 1 from public.originals_episode_views v
                    where v.episode_id = u.episode_id and v.profile_id = u.profile_id
               ),
               (select max(case when coalesce(v.duration_seconds, 0) > 0
                                then least(100, (v.furthest_second * 100) / v.duration_seconds)
                                else 0 end)::int
                  from public.originals_episode_views v
                 where v.episode_id = u.episode_id and v.profile_id = u.profile_id)
        from public.originals_unlocks u
        join public.originals_episodes e on e.id = u.episode_id
        join public.originals_series s on s.id = e.series_id
        left join public.profiles p on p.id = u.profile_id
        where u.created_at >= v_from
    )
    union all
    (
        select 'season_pass'::text,
               sp.profile_id,
               p.full_name,
               p.email,
               p.avatar_url,
               s.title,
               null::int,
               null::text,
               null::int,
               sp.price_inr,
               sp.created_at,
               sp.expires_at,
               null::boolean,
               null::int
        from public.originals_season_passes sp
        join public.originals_series s on s.id = sp.series_id
        left join public.profiles p on p.id = sp.profile_id
        where sp.created_at >= v_from
    )
    )
    select pr.kind, pr.profile_id, pr.full_name, pr.email, pr.avatar_url,
           pr.series_title, pr.episode_number, pr.episode_title,
           pr.credits_spent, pr.price_inr, pr.purchased_at, pr.expires_at,
           pr.watched, pr.percent_watched
    from purchase_rows pr
    order by pr.purchased_at desc
    limit greatest(coalesce(p_limit, 300), 1);
end;
$$;

revoke execute on function public.admin_analytics_purchases(int, int) from public, anon;
grant execute on function public.admin_analytics_purchases(int, int) to authenticated, service_role;

-- The full history of one person: every visit and every episode, in order.
-- Reached from a row in the viewer table, which is where "did they come back"
-- turns into "come back to what".
create or replace function public.admin_analytics_viewer_history(
    p_profile_id uuid default null,
    p_visitor_id uuid default null,
    p_limit int default 100
)
returns table (
    kind text,
    happened_at timestamptz,
    session_id uuid,
    series_title text,
    episode_number int,
    episode_title text,
    percent_watched int,
    seconds_watched int,
    completed boolean,
    access text,
    path text,
    device text
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (select 1 from public.admin_users where id = auth.uid()) then
        raise exception 'Admin access required';
    end if;
    if p_profile_id is null and p_visitor_id is null then
        raise exception 'A profile or a visitor is required';
    end if;

    -- Wrapped for the same reason as `admin_analytics_purchases` above: a
    -- UNION cannot be ordered by an expression column, and the bare name would
    -- have found the OUT parameter instead.
    return query
    with history_rows (
        kind, happened_at, session_id, series_title, episode_number,
        episode_title, percent_watched, seconds_watched, completed, access,
        path, device
    ) as (
    (
        select 'watch'::text,
               v.started_at,
               v.session_id,
               s.title,
               e.episode_number,
               e.title,
               case when coalesce(v.duration_seconds, 0) > 0
                    then least(100, (v.furthest_second * 100) / v.duration_seconds)::int
                    else null end,
               v.seconds_watched,
               v.completed,
               v.access,
               null::text,
               null::text
        from public.originals_episode_views v
        join public.originals_episodes e on e.id = v.episode_id
        join public.originals_series s on s.id = v.series_id
        where (p_profile_id is not null and v.profile_id = p_profile_id)
           or (p_profile_id is null and v.visitor_id = p_visitor_id)
    )
    union all
    (
        select 'visit'::text,
               ses.started_at,
               ses.id,
               null::text,
               null::int,
               null::text,
               null::int,
               null::int,
               null::boolean,
               null::text,
               ses.landing_path,
               ses.device
        from public.analytics_sessions ses
        where (p_profile_id is not null and ses.profile_id = p_profile_id)
           or (p_profile_id is null and ses.visitor_id = p_visitor_id)
    )
    )
    select hr.kind, hr.happened_at, hr.session_id, hr.series_title,
           hr.episode_number, hr.episode_title, hr.percent_watched,
           hr.seconds_watched, hr.completed, hr.access, hr.path, hr.device
    from history_rows hr
    order by hr.happened_at desc
    limit greatest(coalesce(p_limit, 100), 1);
end;
$$;

revoke execute on function public.admin_analytics_viewer_history(uuid, uuid, int) from public, anon;
grant execute on function public.admin_analytics_viewer_history(uuid, uuid, int) to authenticated, service_role;
