"use client"

import Link from "next/link"
import {use,useEffect,useState} from "react"
import {ArrowLeft,ArrowRight,Loader2,LockKeyhole,Sparkles} from "lucide-react"
import Navbar from "@/components/Navbar"
import {useAuth} from "@/components/auth/auth-provider"
import {createClient} from "@/lib/supabase/client"

type Product={id:string;name:string;description:string;product_type:string;price:number;is_free:boolean;active:boolean;image_url:string|null;access_url:string;standalone_purchase:boolean;}
export default function DigitalProductPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params);const {user,signInWithGoogle}=useAuth()
  const [product,setProduct]=useState<Product|null>(null);const [entitled,setEntitled]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("")
  useEffect(()=>{let active=true;const load=async()=>{const supabase=createClient();const {data}=await supabase.from("digital_products").select("*").eq("id",id).eq("active",true).maybeSingle();if(!active)return;setProduct(data as Product|null);if(user){const {data:grants}=await supabase.from("user_entitlements").select("starts_at,expires_at").eq("profile_id",user.id).eq("entitlement_key",`digital_product:${id}`);const now=Date.now();setEntitled((grants||[]).some(g=>Date.parse(g.starts_at)<=now&&(!g.expires_at||Date.parse(g.expires_at)>now)))}};void load();return()=>{active=false}},[id,user])
  const buy=async()=>{if(!user){signInWithGoogle();return}setBusy(true);setMessage("");try{if(product?.is_free){const res=await fetch("/api/products/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const data=await res.json();if(!res.ok)throw new Error(data.error);setEntitled(true)}else{if(!(window as any).Razorpay){const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";await new Promise<void>((resolve,reject)=>{script.onload=()=>resolve();script.onerror=()=>reject(new Error("Could not load payment checkout."));document.body.appendChild(script)})}const res=await fetch("/api/products/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const order=await res.json();if(!res.ok)throw new Error(order.error);const checkout=new (window as any).Razorpay({key:order.keyId,order_id:order.orderId,amount:order.amount,currency:"INR",name:"AI Director Hub",description:order.productName,prefill:{email:order.email,name:order.name},theme:{color:"#b9f42e"},handler:async(payment:any)=>{const verified=await fetch("/api/products/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payment)});const result=await verified.json();if(!verified.ok){setMessage(result.error);setBusy(false);return}setEntitled(true);setBusy(false)},modal:{ondismiss:()=>setBusy(false)}});checkout.open();return}}catch(error){setMessage(error instanceof Error?error.message:"Could not complete the request.")}setBusy(false)}
  return <main className="min-h-screen bg-[#070807] text-white"><Navbar/><div className="mx-auto max-w-5xl px-5 pb-20 pt-32 sm:px-8"><Link href="/learn" className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft className="h-4 w-4"/> Academy</Link>{!product?<div className="py-20 text-center"><Loader2 className="mx-auto animate-spin text-primary"/></div>:<div className="mt-8 grid gap-10 md:grid-cols-2 md:items-center">{product.image_url?<img src={product.image_url} alt="" className="aspect-square w-full rounded-2xl object-cover"/>:<div className="grid aspect-square place-items-center rounded-2xl border border-white/10 bg-white/[.03]"><Sparkles className="h-16 w-16 text-primary"/></div>}<div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">{product.product_type}</p><h1 className="mt-3 text-4xl font-semibold">{product.name}</h1><p className="mt-5 whitespace-pre-line leading-relaxed text-white/60">{product.description}</p><p className="mt-6 text-xl font-semibold">{product.is_free?"Free":`₹${product.price}`}</p>{entitled?<div className="mt-7 space-y-3"><p className="inline-flex items-center gap-2 text-sm text-primary"><Sparkles className="h-4 w-4"/>You have access to this product.</p>{product.access_url&&<a href={product.access_url} target="_blank" rel="noreferrer" className="flex h-12 items-center justify-center gap-2 rounded-lg bg-primary px-5 font-semibold text-black">Open Product <ArrowRight className="h-4 w-4"/></a>}</div>:<button disabled={busy||(!product.is_free&&!product.standalone_purchase)} onClick={()=>void buy()} className="mt-7 flex h-12 items-center justify-center gap-2 rounded-lg bg-primary px-6 font-semibold text-black disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:product.is_free?"Get Free Access":<><LockKeyhole className="h-4 w-4"/>Purchase Product · ₹{product.price}</>}</button>}{!product.is_free&&!product.standalone_purchase&&<p className="mt-3 text-xs text-white/45">Included with selected courses or coaching.</p>}{message&&<p role="alert" className="mt-4 text-sm text-red-300">{message}</p>}</div></div>}</div></main>
}
